parameters:
#    fastre_budget.example.class: Fastre\BudgetBundle\Example

services:
  neo4jclient:
    class: Everyman\Neo4j\Client
    arguments: [%neo4j_host%, %neo4j_port%]
#    fastre_budget.example:
#        class: %fastre_budget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
